/**
 * Copyright (C) 2021-2024 Saturneric <eric@bktus.com>
 *
 * This file is part of GpgFrontend.
 *
 * GpgFrontend is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GpgFrontend is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GpgFrontend. If not, see <https://www.gnu.org/licenses/>.
 *
 * The initial version of the source code is inherited from
 * the gpg4usb project, which is under GPL-3.0-or-later.
 *
 * All the source code of GpgFrontend was modified and released by
 * Saturneric <eric@bktus.com> starting on May 12, 2021.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#pragma once

#include "GFResExport.h"  // generated by register_library -> GF_RES_EXPORT

namespace GpgFrontend {

/**
 * @brief Register every Qt resource embedded in libgf_res: the /icons prefix
 *        (resource/qrc/icons.qrc), the /test prefixes (resource/qrc/test.qrc),
 *        TRANSLATORS (resource/qrc/app.qrc), plus the GpgFrontend (/i18n) and Qt
 *        (/i18n_qt) translation catalogs.
 *
 * Must be called exactly once, before any ":/..." resource is accessed (i.e. as
 * the first statement of main()). The resources live in this shared library
 * rather than the executable, so the executable itself carries no embedded
 * resources.
 */
GF_RES_EXPORT void InitResources();

}  // namespace GpgFrontend
