/**
 * Copyright (C) 2021-2024 Saturneric <eric@bktus.com>
 *
 * This file is part of GpgFrontend.
 *
 * GpgFrontend is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GpgFrontend is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GpgFrontend. If not, see <https://www.gnu.org/licenses/>.
 *
 * The initial version of the source code is inherited from
 * the gpg4usb project, which is under GPL-3.0-or-later.
 *
 * All the source code of GpgFrontend was modified and released by
 * Saturneric <eric@bktus.com> starting on May 12, 2021.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#include <sodium.h>

#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QSaveFile>
#include <QTextStream>

/**
 * @file main.cpp
 * @brief Generate the one module-build keypair a Host build signs with.
 *
 * ## What this key is, and is not
 *
 * It is **build-scoped and ephemeral**: one keypair per build tree, used to
 * sign every `.gfmodule` descriptor that build produces, with the public half
 * compiled into the Host so verification is offline and needs no catalog. It
 * is **not** a publisher identity, is never exported, never uploaded, and is
 * meant to be discarded with the workspace that made it.
 *
 * ## Why this is its own tool
 *
 * It must not link gf_core. gf_core consumes this tool's output -- the
 * generated source carrying the public key -- so linking it here would be a
 * dependency cycle. Qt::Core and libsodium are the whole of what it needs.
 *
 * ## Fail-closed, deliberately
 *
 * The dangerous case is not a missing key but a *replaced* one: a Host already
 * carrying public key A, and modules freshly signed with private key B. Every
 * signature verifies against its own key, every test passes, and nothing loads
 * on a user's machine. So this refuses to guess. See Decide() for the table.
 */

namespace {

constexpr auto kSeedFile = "module-build.seed";
constexpr auto kPublicFile = "module-build.pub";
constexpr auto kBuildIdFile = "build-id";

auto ReadAll(const QString& path) -> QByteArray {
  QFile f(path);
  if (!f.open(QIODevice::ReadOnly)) return {};
  const auto bytes = f.readAll();
  f.close();
  return bytes;
}

/// Write via QSaveFile so a failure leaves the previous content, not a stub.
auto WriteAll(const QString& path, const QByteArray& bytes,
              QFile::Permissions permissions) -> bool {
  QSaveFile out(path);
  if (!out.open(QIODevice::WriteOnly)) return false;
  if (out.write(bytes) != bytes.size()) {
    out.cancelWriting();
    return false;
  }
  if (!out.commit()) return false;
  return QFile::setPermissions(path, permissions);
}

/// The generated translation unit gf_core compiles.
///
/// A source file rather than a header: a header would be included by whatever
/// happened to reach for it, and the key belongs to exactly one definition.
/// `0x47, 0x2a, ...` -- shared so the generator and the comparison in Decide()
/// cannot format the same bytes two different ways.
auto HexByteList(const QByteArray& bytes) -> QString {
  QString out;
  for (const auto byte : bytes) {
    out += QString::asprintf("0x%02x, ", static_cast<unsigned char>(byte));
  }
  return out.trimmed();
}

auto GeneratedSource(const QByteArray& public_key, const QString& build_id)
    -> QByteArray {
  const auto bytes = HexByteList(public_key);

  return QString(R"(// GENERATED by gf_module_keygen. Do not edit, do not commit.
//
// The module-build trust root for this build tree. The public half of an
// ephemeral Ed25519 keypair whose private half never leaves the workspace,
// plus the build identity every descriptor this build signs must carry.
//
// Regenerating this file while descriptors signed by the old key still exist
// makes those descriptors unloadable. gf_module_keygen refuses to do so.

#include <QByteArray>
#include <QString>

namespace GpgFrontend::Module::generated {

// `extern` is load-bearing: a `const` at namespace scope has INTERNAL linkage
// in C++, so without it these are three definitions nothing outside this
// translation unit can see, and ModuleTrustRoot.cpp fails to link.
extern const unsigned char kModuleBuildPublicKey[];
extern const int kModuleBuildPublicKeySize;
extern const char kModuleBuildId[];

extern const unsigned char kModuleBuildPublicKey[] = {%1};
extern const int kModuleBuildPublicKeySize = %2;
extern const char kModuleBuildId[] = "%3";

}  // namespace GpgFrontend::Module::generated
)")
      .arg(bytes)
      .arg(public_key.size())
      .arg(build_id)
      .toUtf8();
}

enum class Decision { kGenerate, kReuse, kRefuse };

/**
 * @brief Decide from observed state, never from a flag.
 *
 * | trust source | seed    | derived == stored | build id | action     |
 * | ------------ | ------- | ----------------- | -------- | ---------- |
 * | absent       | absent  | -                 | -        | generate   |
 * | absent       | present | -                 | -        | generate   |
 * | present      | absent  | -                 | -        | **refuse** |
 * | present      | present | no                | -        | **refuse** |
 * | present      | present | yes               | differs  | generate   |
 * | present      | present | yes               | same     | reuse      |
 *
 * ## What actually makes a row dangerous
 *
 * Not "something changed" but "something changed that the build graph cannot
 * repair". gf_core compiles the trust root source, and every descriptor is
 * regenerated when it changes, so rewriting that file relinks the Host and
 * re-signs every module together. Anything reachable that way is safe.
 *
 * So a **changed build id regenerates**. A new commit is a new product and a
 * new build id, which during development is every commit; refusing there would
 * mean hand-deleting a directory after each one, to prevent a mismatch the
 * build graph was going to fix anyway. (This plan said refuse. Running it said
 * otherwise, on the first commit that followed.)
 *
 * The two rows that stay refusals are the ones where the trust root is present
 * -- so gf_core is up to date and will NOT relink -- while the seed is gone or
 * derives a different key. Signing there would produce descriptors the Host
 * beside them carries no key for, and nothing in the build would notice. Both
 * are recoverable by deleting the pair, which is what the message says.
 */
auto Decide(const QString& key_dir, const QString& source_out,
            const QString& build_id, QString& reason) -> Decision {
  const auto have_source = QFileInfo::exists(source_out);
  const auto seed = ReadAll(key_dir + "/" + kSeedFile);
  const auto have_seed = seed.size() == crypto_sign_SEEDBYTES;

  // An orphaned seed is worthless without the trust root it belongs to, and
  // the Host will relink from whatever is written now, so this is a fresh
  // start rather than a conflict.
  if (!have_source) return Decision::kGenerate;

  const auto remedy = QString(
                          "\n  Delete \"%1\" and \"%2\", then rebuild the "
                          "Host and every module together.")
                          .arg(source_out, key_dir);

  if (!have_seed) {
    reason = "the Host trust root exists but its module-build seed is gone. "
             "A new key would sign descriptors the already-built Host will "
             "refuse." +
             remedy;
    return Decision::kRefuse;
  }

  // Derive and compare rather than trusting the stored public file: the seed
  // is the only thing that actually determines what will sign.
  std::array<unsigned char, crypto_sign_PUBLICKEYBYTES> derived{};
  std::array<unsigned char, crypto_sign_SECRETKEYBYTES> secret{};
  if (crypto_sign_seed_keypair(
          derived.data(), secret.data(),
          reinterpret_cast<const unsigned char*>(seed.constData())) != 0) {
    reason = "the stored module-build seed could not be used" + remedy;
    return Decision::kRefuse;
  }
  sodium_memzero(secret.data(), secret.size());

  // Compare the KEY, not the whole file: the file also carries the build id,
  // and a changed build id is a legitimate reason to rewrite it.
  const auto stored_source = ReadAll(source_out);
  const QByteArray key_marker =
      "const unsigned char kModuleBuildPublicKey[] = {" +
      HexByteList(QByteArray(reinterpret_cast<const char*>(derived.data()),
                             static_cast<qsizetype>(derived.size())))
          .toUtf8();
  if (!stored_source.contains(key_marker)) {
    reason =
        "the module-build seed does not derive the key the Host trust root "
        "carries. Descriptors signed with it could not be loaded by the Host "
        "that was built beside them." +
        remedy;
    return Decision::kRefuse;
  }

  const auto derived_source = GeneratedSource(
      QByteArray(reinterpret_cast<const char*>(derived.data()),
                 static_cast<qsizetype>(derived.size())),
      build_id);

  // Same key, different build id: rewrite, which relinks the Host and
  // re-signs every descriptor from the same key. Consistent either way.
  if (stored_source != derived_source) return Decision::kGenerate;

  return Decision::kReuse;
}

}  // namespace

auto main(int argc, char** argv) -> int {
  QCoreApplication app(argc, argv);
  QTextStream err(stderr);

  QString key_dir;
  QString source_out;
  QString build_id;

  const auto args = QCoreApplication::arguments();
  for (auto i = 1; i < args.size(); ++i) {
    const auto& flag = args.at(i);
    const auto value = [&]() -> QString {
      if (i + 1 >= args.size()) return {};
      return args.at(++i);
    };

    if (flag == "--key-dir") {
      key_dir = value();
    } else if (flag == "--source-out") {
      source_out = value();
    } else if (flag == "--build-id") {
      build_id = value();
    } else {
      err << "gf_module_keygen: unknown argument: " << flag << "\n";
      return 2;
    }
  }

  if (key_dir.isEmpty() || source_out.isEmpty() || build_id.isEmpty()) {
    err << "usage: gf_module_keygen --key-dir DIR --source-out FILE "
           "--build-id ID\n";
    return 2;
  }

  if (sodium_init() < 0) {
    err << "gf_module_keygen: the cryptography library could not be started\n";
    return 1;
  }

  if (!QDir().mkpath(key_dir) ||
      !QDir().mkpath(QFileInfo(source_out).absolutePath())) {
    err << "gf_module_keygen: the output directories could not be made\n";
    return 1;
  }

  QString reason;
  switch (Decide(key_dir, source_out, build_id, reason)) {
    case Decision::kReuse:
      // Nothing is rewritten, so nothing downstream rebuilds. Touch the
      // outputs instead, so the build graph sees them as satisfied.
      return 0;
    case Decision::kRefuse:
      err << "gf_module_keygen: " << reason << "\n";
      return 1;
    case Decision::kGenerate:
      break;
  }

  // Reached for a fresh tree, an orphaned seed, or a changed build id. In the
  // last case the existing seed is deliberately replaced: a build id is part
  // of what the key attests to, and carrying one key across two build
  // identities would make the pair ambiguous.
  std::array<unsigned char, crypto_sign_SEEDBYTES> seed{};
  std::array<unsigned char, crypto_sign_PUBLICKEYBYTES> public_key{};
  std::array<unsigned char, crypto_sign_SECRETKEYBYTES> secret_key{};

  randombytes_buf(seed.data(), seed.size());
  if (crypto_sign_seed_keypair(public_key.data(), secret_key.data(),
                               seed.data()) != 0) {
    sodium_memzero(seed.data(), seed.size());
    err << "gf_module_keygen: a module-build key could not be generated\n";
    return 1;
  }
  // The secret key is derivable from the seed and is not what gets stored;
  // wipe the expanded copy as soon as the public half has been taken from it.
  sodium_memzero(secret_key.data(), secret_key.size());

  const QByteArray seed_bytes(reinterpret_cast<const char*>(seed.data()),
                              static_cast<qsizetype>(seed.size()));
  const QByteArray public_bytes(
      reinterpret_cast<const char*>(public_key.data()),
      static_cast<qsizetype>(public_key.size()));

  // Owner-only, and it never leaves this directory: no install rule reads it,
  // no staging step copies it, and nothing uploads it. That containment is the
  // actual guarantee; the cleanup step that removes it afterwards is
  // best-effort workspace hygiene and not secure erasure.
  const auto ok =
      WriteAll(key_dir + "/" + kSeedFile, seed_bytes,
               QFile::ReadOwner | QFile::WriteOwner) &&
      WriteAll(key_dir + "/" + kPublicFile, public_bytes.toHex() + "\n",
               QFile::ReadOwner | QFile::WriteOwner | QFile::ReadGroup |
                   QFile::ReadOther) &&
      WriteAll(key_dir + "/" + kBuildIdFile, build_id.toUtf8() + "\n",
               QFile::ReadOwner | QFile::WriteOwner | QFile::ReadGroup |
                   QFile::ReadOther) &&
      WriteAll(source_out, GeneratedSource(public_bytes, build_id),
               QFile::ReadOwner | QFile::WriteOwner | QFile::ReadGroup |
                   QFile::ReadOther);

  sodium_memzero(seed.data(), seed.size());

  if (!ok) {
    err << "gf_module_keygen: the module-build key could not be written\n";
    return 1;
  }

  QTextStream(stdout) << "module-build key for " << build_id << "\n";
  return 0;
}
