# Copyright (C) 2021-2024 Saturneric <eric@bktus.com>
#
# This file is part of GpgFrontend.
#
# GpgFrontend is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GpgFrontend is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GpgFrontend. If not, see <https://www.gnu.org/licenses/>.
#
# The initial version of the source code is inherited from
# the gpg4usb project, which is under GPL-3.0-or-later.
#
# All the source code of GpgFrontend was modified and released by
# Saturneric <eric@bktus.com> starting on May 12, 2021.
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Develop CI Qt6

on:
  push:
    branches: ["develop", "dev/**"]
    paths-ignore:
      - "resource/lfs/locale/**"
      - "**.md"
env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest-server
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: "false"
          submodules: recursive

      - name: Get Short SHA of Commit
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Cache APT packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('.gitea/workflows/develop-qt6.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Install Dependence
        run: |
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt-get update
          sudo apt-get -y install build-essential binutils git cmake ccache
          sudo apt-get -y install autoconf automake gettext texinfo
          sudo apt-get -y install gcc g++ ninja-build gnupg qtchooser qt6-base-dev qt6-base-dev-tools qt6-l10n-tools qt6-tools-dev qt6-tools-dev-tools libqt6svg6
          sudo apt-get -y install libarchive-dev libssl-dev libgpgme-dev libgl1-mesa-dev libfuse2

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.os }}

      - name: Cache googletest
        id: cache-googletest
        uses: actions/cache@v3
        with:
          path: |
            ${{github.workspace}}/third_party/googletest
            /usr/local/lib/libgtest*
            /usr/local/lib/libgmock*
            /usr/local/include/gtest
            /usr/local/include/gmock
          key: ${{ runner.os }}-googletest-v1.15.0
          restore-keys: |
            ${{ runner.os }}-googletest-

      - name: Build googletest
        if: steps.cache-googletest.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 --branch v1.15.0 https://github.com/google/googletest.git ${{github.workspace}}/third_party/googletest
          cd ${{github.workspace}}/third_party/googletest
          mkdir build && cd build
          cmake -G Ninja -DBUILD_SHARED_LIBS=ON ..
          ninja
          sudo ninja install

      - name: Build GpgFrontend
        run: |
          cmake -B ${{github.workspace}}/build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DGPGFRONTEND_LINK_GPGME_INTO_CORE=ON
          cmake --build ${{github.workspace}}/build --config {{$env.BUILD_TYPE}} -- -v

      - name: Run Unit Tests
        run: |
          cd ${{github.workspace}}/build/artifacts
          export QT_QPA_PLATFORM=offscreen
          export GTEST_OUTPUT=json:${{github.workspace}}/build/artifacts/unit_tests.json
          ./gpgfrontend -t || true
