/**
 * Copyright (C) 2021-2024 Saturneric <eric@bktus.com>
 *
 * This file is part of GpgFrontend.
 *
 * GpgFrontend is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GpgFrontend is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GpgFrontend. If not, see <https://www.gnu.org/licenses/>.
 *
 * The initial version of the source code is inherited from
 * the gpg4usb project, which is under GPL-3.0-or-later.
 *
 * All the source code of GpgFrontend was modified and released by
 * Saturneric <eric@bktus.com> starting on May 12, 2021.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#pragma once

#include "GFCoreExport.h"

namespace GpgFrontend::Module {

/**
 * @file ModulePublisherKey.h
 * @brief The persistent key an external module's publisher signs with.
 *
 * ## Not the build key
 *
 * The integrated trust domain has one key per build tree, generated by
 * gf_module_keygen and discarded with the workspace. A publisher key is the
 * opposite on every axis: persistent, held by a person, and never compiled
 * into anything. Nothing here reads or writes the build key, and the builder
 * refuses a publisher seed that happens to derive it.
 *
 * ## Identity
 *
 * The publisher IS its 32-byte Ed25519 public key. There is no hashed or
 * truncated key id: an Ed25519 key is already short enough to compare whole,
 * and an id derived from it would add nothing but a way to collide. The
 * canonical text is the key in lower-case hex, which is also what the trust
 * store records; the grouped upper-case form is for people only.
 *
 * A publisher's name or URL is never part of the identity. They may travel as
 * manifest metadata, where they are claims and nothing more.
 *
 * ## Typed files
 *
 * Both files open with a header line naming what they are. The point is what
 * a header refuses: a raw 32-byte seed -- which is exactly what
 * `module-build.seed` is -- cannot be read as a publisher key, so the build key
 * cannot become a publisher identity by someone passing the wrong file.
 *
 * ```
 * gf-module-publisher-secret-v1
 * <64 lower-case hex: the 32-byte Ed25519 seed>
 * ```
 *
 * Pure: no settings, no profile, no singletons. The externalize tool depends
 * on that, and so does anything that wants a fingerprint without a trust
 * store attached.
 */

/// The first line of a publisher secret key file.
constexpr auto kModulePublisherSecretKeyHeader =
    "gf-module-publisher-secret-v1";

/// The first line of a publisher public key file.
constexpr auto kModulePublisherPublicKeyHeader =
    "gf-module-publisher-public-v1";

/**
 * @brief The canonical spelling of a publisher key: 64 lower-case hex.
 *
 * What the trust store records and matches on. Empty for a key that is not
 * 32 bytes, so a malformed key has no spelling that could match anything.
 */
auto GF_CORE_EXPORT ModulePublisherKeyText(const QByteArray& public_key)
    -> QString;

/**
 * @brief The fingerprint of a publisher key, for showing a person.
 *
 * Derived, never stored. Grouped the way every other fingerprint in this
 * application is, so it reads the same way.
 */
auto GF_CORE_EXPORT ModulePublisherKeyFingerprint(const QByteArray& public_key)
    -> QString;

/**
 * @brief The public key a 32-byte seed derives.
 *
 * @return the 32 raw bytes, or empty if @p seed is not a usable seed
 */
auto GF_CORE_EXPORT ModulePublisherPublicKeyFromSeed(const QByteArray& seed)
    -> QByteArray;

/**
 * @brief Parse the contents of a publisher secret key file.
 *
 * Strict: the header line, then exactly 64 lower-case hex characters, then at
 * most one line ending. Anything else is refused -- a raw seed in particular.
 *
 * @param[out] seed the 32-byte seed; the caller wipes it
 */
auto GF_CORE_EXPORT ParseModulePublisherSecretKey(const QByteArray& contents,
                                                  QByteArray& seed,
                                                  QString& reason) -> bool;

/// As ParseModulePublisherSecretKey(), for a public key file.
auto GF_CORE_EXPORT ParseModulePublisherPublicKey(const QByteArray& contents,
                                                  QByteArray& public_key,
                                                  QString& reason) -> bool;

/**
 * @brief Read a publisher secret key file.
 *
 * The file's own buffer is wiped once the seed has been taken from it.
 *
 * @param[out] seed the 32-byte seed; the caller wipes it
 */
auto GF_CORE_EXPORT ReadModulePublisherSecretKey(const QString& path,
                                                 QByteArray& seed,
                                                 QString& reason) -> bool;

/**
 * @brief Read a publisher key file of either kind, for its public key.
 *
 * A secret key file is accepted and its public half derived, so "what is the
 * fingerprint of the key I sign with" does not need the public file at hand.
 */
auto GF_CORE_EXPORT ReadModulePublisherPublicKey(const QString& path,
                                                 QByteArray& public_key,
                                                 QString& reason) -> bool;

/**
 * @brief Whether a secret key file can be read by anyone but its owner.
 *
 * Always false where POSIX permissions do not apply. Advisory: the caller
 * decides whether to warn.
 */
auto GF_CORE_EXPORT IsModulePublisherSecretKeyExposed(const QString& path)
    -> bool;

/**
 * @brief Generate a fresh publisher key and write both files.
 *
 * Refuses to replace either file: a publisher key is an identity, and
 * overwriting one silently would orphan every module signed with it. The
 * secret file is owner-only.
 *
 * @param[out] public_key the new public key
 */
auto GF_CORE_EXPORT GenerateModulePublisherKeyFiles(const QString& secret_path,
                                                    const QString& public_path,
                                                    QByteArray& public_key,
                                                    QString& reason) -> bool;

}  // namespace GpgFrontend::Module
