/**
 * Copyright (C) 2021-2024 Saturneric <eric@bktus.com>
 *
 * This file is part of GpgFrontend.
 *
 * GpgFrontend is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GpgFrontend is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GpgFrontend. If not, see <https://www.gnu.org/licenses/>.
 *
 * The initial version of the source code is inherited from
 * the gpg4usb project, which is under GPL-3.0-or-later.
 *
 * All the source code of GpgFrontend was modified and released by
 * Saturneric <eric@bktus.com> starting on May 12, 2021.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#include "core/module/ModuleTrustRoot.h"

namespace GpgFrontend::Module {

// Defined by ModuleTrustRootGenerated.cpp, which gf_module_keygen writes into
// the build tree. Declared here rather than included from a generated header:
// a header would be reachable by anything that went looking, and the key
// belongs to exactly one definition and one accessor.
namespace generated {
extern const unsigned char kModuleBuildPublicKey[];
extern const int kModuleBuildPublicKeySize;
extern const char kModuleBuildId[];
}  // namespace generated

auto ModuleBuildPublicKey() -> const QByteArray& {
  // Built once from the generated bytes. A copy rather than a view over them,
  // so nothing downstream can be handed a pointer whose lifetime it has to
  // reason about.
  static const QByteArray key(
      reinterpret_cast<const char*>(generated::kModuleBuildPublicKey),
      static_cast<qsizetype>(generated::kModuleBuildPublicKeySize));
  return key;
}

auto ModuleBuildId() -> const QString& {
  static const QString id = QString::fromLatin1(generated::kModuleBuildId);
  return id;
}

}  // namespace GpgFrontend::Module
